import type { Metadata } from "next";
import {Inter , IBM_Plex_Mono } from "next/font/google";
import "allotment/dist/style.css" 
import "./globals.css";
import { ThemeProvider } from "@/components/themeprovider";
import { Providers } from "@/components/providers";
import { Toaster } from "sonner";

const inter = Inter({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const plexMono = IBM_Plex_Mono({
  variable: "--font-plex-mono",
  subsets: ["latin"],
  weight: ["400","500","600","700"]
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${inter.variable} ${plexMono.variable} antialiased`}
      >
        <Providers>
        {children}
        <Toaster/>

        </Providers>
       
       
      </body>
    </html>
  );
}
